# Starship Configuration
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# General Configuration
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$ruby\
$nodejs\
$package\
$fill\
$line_break\
$character"""

right_format = """
$cmd_duration\
$jobs"""

# Timeout for commands to execute (in milliseconds)
command_timeout = 500

# Disable the new line at the start of the prompt
add_newline = true

# Character module - shows prompt symbol
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[I](bold green)"

# Directory module
[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"

# Git modules
[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

# Programming languages
[ruby]
symbol = " "
format = "using [$symbol($version )]($style)"
detect_extensions = ["rb"]
detect_files = ["Gemfile", ".ruby-version"]
detect_folders = []
style = "bold red"

[nodejs]
symbol = " "
format = "using [$symbol($version )]($style)"
detect_extensions = ["js", "mjs", "cjs", "ts", "tsx"]
detect_files = ["package.json", ".node-version", ".nvmrc"]
detect_folders = ["node_modules"]
style = "bold green"

# Package version
[package]
symbol = "pkg "
format = "[$symbol$version]($style) "
display_private = false
disabled = false

# Command duration
[cmd_duration]
min_time = 2_000 # Show command duration over 2,000 milliseconds (2 seconds)
format = "took [$duration]($style) "
style = "bold yellow"

# Jobs
[jobs]
symbol = "✦"
number_threshold = 1
format = "[$symbol$number]($style) "
style = "bold blue"

# Username
[username]
style_user = "bold dimmed blue"
show_always = false
format = "[$user]($style) "

# Hostname
[hostname]
ssh_only = true
format = "[@$hostname]($style) "
style = "bold dimmed green"

# Fill module - fills space between left and right prompt
[fill]
symbol = " "

# Line break
[line_break]
disabled = false